#!/usr/bin/env python3
"""
One-command end-to-end demo of the SYNTHETIC IoT sensor-to-cloud pipeline.

    python3 run_pipeline.py [--loss 0.1] [--nodes 3] [--readings 240] [--seed 7]

What it does:
  1. Starts the mock cloud ingest server (localhost HTTP).
  2. Runs synthetic sensor nodes -> lossy wireless link (with ARQ retries)
     -> gateway (CRC check, dedup, batching) -> cloud.
  3. Sweeps several link-loss rates and measures delivery rate.
  4. Writes plots + dashboard.html + results/summary.json.

Everything is simulated; no real hardware, network, or CISNR data involved.
"""

import argparse
import base64
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from sensors.node import SensorNode, make_packet, serialize
from wireless.link import WirelessLink, ReliableSender
from gateway.aggregator import Gateway
from cloud.ingest import CloudServer
from analysis import metrics, plots

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results")


def run_simulation(num_nodes, readings_per_node, link_kwargs, sender_kwargs,
                   cloud_url=None, seed=7, interval_s=5.0, batch_size=20,
                   collect_samples=False):
    """Run one full synthetic pipeline pass. Returns (generated, gateway, samples)."""
    nodes = [SensorNode(f"node-{i}", seed=seed + i, interval_s=interval_s)
             for i in range(num_nodes)]
    link = WirelessLink(seed=seed, **link_kwargs)
    sender = ReliableSender(link, **sender_kwargs)
    gateway = Gateway(cloud_url=cloud_url, batch_size=batch_size)

    generated = 0
    samples = []
    for node in nodes:
        for seq in range(readings_per_node):
            t = seq * interval_s + hash(node.node_id) % 3  # small per-node offset
            reading = node.generate_reading(seq, float(t))
            if collect_samples and node.node_id == "node-0":
                samples.append(reading)
            packet = make_packet(reading)
            raw = serialize(packet)
            sender.send(raw, float(t), gateway.receive)
            generated += 1
    gateway.flush()
    return generated, gateway, samples


def b64img(path):
    with open(path, "rb") as f:
        return "data:image/png;base64," + base64.b64encode(f.read()).decode()


def build_dashboard(summary, sweep, gateway_stats, img_uris, out_path):
    """Static HTML dashboard for one synthetic run."""
    lat = summary
    cards = [
        ("Readings generated", f"{lat['generated']}"),
        ("Delivered to cloud", f"{lat['accepted_unique']}"),
        ("Delivery rate", f"{lat['delivery_rate']:.1%}"),
        ("CRC failure rate", f"{lat['crc_failure_rate']:.2%}"),
        ("Duplicate rate", f"{lat['duplicate_rate']:.2%}"),
        ("Latency p50 / p90 / p99", f"{lat['latency_p50_s']:.2f}s / {lat['latency_p90_s']:.2f}s / {lat['latency_p99_s']:.2f}s"),
    ]
    card_html = "\n".join(
        f'<div class="card"><div class="k">{k}</div><div class="v">{v}</div></div>'
        for k, v in cards
    )
    sweep_rows = "\n".join(
        f"<tr><td>{lr:.0%}</td><td>{dr:.1%}</td></tr>"
        for lr, dr in sweep
    )
    charts = "\n".join(
        f'<figure><img src="{uri}" alt="{name}"><figcaption>{name} — synthetic simulation</figcaption></figure>'
        for name, uri in img_uris
    )
    html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>IoT Sensor-to-Cloud Pipeline — Synthetic Demo Dashboard</title>
<style>
body{{font-family:system-ui,sans-serif;max-width:980px;margin:2rem auto;padding:0 1rem;color:#1f2937}}
.banner{{background:#fef3c7;border:2px solid #d97706;border-radius:8px;padding:1rem;margin-bottom:1.5rem}}
.cards{{display:grid;grid-template-columns:repeat(3,1fr);gap:0.8rem;margin:1rem 0}}
.card{{border:1px solid #e5e7eb;border-radius:8px;padding:0.9rem;background:#f9fafb}}
.k{{font-size:0.8rem;color:#6b7280}}.v{{font-size:1.3rem;font-weight:700;color:#0f766e}}
figure{{margin:1.5rem 0}}img{{max-width:100%;border:1px solid #e5e7eb;border-radius:8px}}
figcaption{{font-size:0.8rem;color:#6b7280;text-align:center}}
table{{border-collapse:collapse;margin:1rem 0}}td,th{{border:1px solid #d1d5db;padding:0.4rem 0.9rem}}
svg.pipe{{width:100%;height:120px}}
pre{{background:#f3f4f6;padding:1rem;border-radius:8px;overflow-x:auto}}
</style></head><body>
<div class="banner"><strong>SYNTHETIC DEMONSTRATION.</strong> All data on this page was
generated by a simulator for teaching purposes. It is inspired by the <em>architecture</em>
of the CISNR E.&nbsp;coli rapid-detection project — it is not the real system and contains
none of its data.</div>
<h1>IoT Sensor-to-Cloud Pipeline — Demo Dashboard</h1>

<svg class="pipe" viewBox="0 0 960 120" xmlns="http://www.w3.org/2000/svg">
<defs><marker id="a" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#0f766e"/></marker></defs>
<rect x="10" y="30" width="150" height="60" rx="10" fill="#0f766e"/><text x="85" y="65" fill="#fff" text-anchor="middle" font-size="14">Sensor nodes</text>
<line x1="160" y1="60" x2="300" y2="60" stroke="#0f766e" stroke-width="2" marker-end="url(#a)"/><text x="230" y="50" text-anchor="middle" font-size="12" fill="#6b7280">lossy radio + ARQ</text>
<rect x="300" y="30" width="150" height="60" rx="10" fill="#d97706"/><text x="375" y="65" fill="#fff" text-anchor="middle" font-size="14">Gateway</text>
<line x1="450" y1="60" x2="590" y2="60" stroke="#0f766e" stroke-width="2" marker-end="url(#a)"/><text x="520" y="50" text-anchor="middle" font-size="12" fill="#6b7280">batched HTTPS</text>
<rect x="590" y="30" width="150" height="60" rx="10" fill="#2563eb"/><text x="665" y="65" fill="#fff" text-anchor="middle" font-size="14">Cloud ingest</text>
<line x1="740" y1="60" x2="880" y2="60" stroke="#0f766e" stroke-width="2" marker-end="url(#a)"/><text x="810" y="50" text-anchor="middle" font-size="12" fill="#6b7280">JSON API</text>
<rect x="880" y="30" width="70" height="60" rx="10" fill="#6b7280"/><text x="915" y="65" fill="#fff" text-anchor="middle" font-size="14">App</text>
</svg>

<h2>Run metrics (simulated)</h2>
<div class="cards">{card_html}</div>

<h2>Delivery rate vs. link loss (simulated sweep)</h2>
<table><tr><th>Link loss</th><th>Delivery rate</th></tr>{sweep_rows}</table>

<h2>Charts</h2>
{charts}

<h2>Gateway counters (simulated)</h2>
<pre>{json.dumps(gateway_stats, indent=2)}</pre>
<p><small>Generated by <code>run_pipeline.py</code>. All numbers are simulation outputs.</small></p>
</body></html>"""
    with open(out_path, "w") as f:
        f.write(html)


def main():
    ap = argparse.ArgumentParser(description="Synthetic IoT sensor-to-cloud pipeline demo")
    ap.add_argument("--loss", type=float, default=0.10, help="wireless link loss rate")
    ap.add_argument("--nodes", type=int, default=3, help="sensor nodes")
    ap.add_argument("--readings", type=int, default=240, help="readings per node (main run)")
    ap.add_argument("--seed", type=int, default=7, help="RNG seed (reproducible)")
    args = ap.parse_args()

    os.makedirs(RESULTS, exist_ok=True)

    # 1. Mock cloud.
    cloud = CloudServer(jsonl_path=os.path.join(RESULTS, "cloud_readings.jsonl")).start()
    print(f"[cloud] mock ingest API at {cloud.url}")

    link_kwargs = dict(loss_rate=args.loss, corrupt_rate=0.02,
                       latency_mean_ms=120.0, latency_std_ms=45.0)
    sender_kwargs = dict(max_retries=3, base_backoff_s=0.4)

    # 2. Main run -> cloud.
    print(f"[sim] main run: {args.nodes} nodes x {args.readings} readings, "
          f"loss={args.loss:.0%}")
    generated, gateway, samples = run_simulation(
        args.nodes, args.readings, link_kwargs, sender_kwargs,
        cloud_url=cloud.url, seed=args.seed, collect_samples=True,
    )
    summary = metrics.summarize_run(generated, gateway)
    print(f"[sim] delivered {summary['accepted_unique']}/{summary['generated']} "
          f"({summary['delivery_rate']:.1%}), cloud stored: {cloud.reading_count()}")

    # 3. Loss sweep (smaller, no cloud — analysis only).
    sweep_losses = [0.0, 0.05, 0.10, 0.20, 0.30]
    sweep = []
    for lr in sweep_losses:
        lk = dict(link_kwargs); lk["loss_rate"] = lr
        gen, gw, _ = run_simulation(3, 80, lk, sender_kwargs,
                                    cloud_url=None, seed=args.seed)
        dr = metrics.delivery_rate(gen, gw.accepted)
        sweep.append((lr, dr))
        print(f"[sweep] loss={lr:.0%} -> delivery={dr:.1%}")

    # 4. Plots.
    p_delivery = os.path.join(RESULTS, "delivery_vs_loss.png")
    p_latency = os.path.join(RESULTS, "latency_cdf.png")
    p_outcomes = os.path.join(RESULTS, "gateway_outcomes.png")
    p_series = os.path.join(RESULTS, "sample_timeseries.png")
    plots.plot_delivery_vs_loss([s[0] for s in sweep], [s[1] for s in sweep], p_delivery)
    plots.plot_latency_cdf(gateway.latencies_s, p_latency)
    plots.plot_gateway_outcomes(gateway.stats(), p_outcomes)
    plots.plot_sample_timeseries(samples, p_series)
    print("[plots] wrote 4 charts to results/")

    # 5. Summary + dashboard.
    with open(os.path.join(RESULTS, "summary.json"), "w") as f:
        json.dump({"run": summary, "sweep": sweep,
                   "gateway": gateway.stats()}, f, indent=2)
    build_dashboard(
        summary, sweep, gateway.stats(),
        [("Delivery vs loss", b64img(p_delivery)),
         ("Latency CDF", b64img(p_latency)),
         ("Gateway outcomes", b64img(p_outcomes)),
         ("Sample sensor stream", b64img(p_series))],
        os.path.join(RESULTS, "dashboard.html"),
    )
    # Also copy dashboard to project root for easy opening.
    with open(os.path.join(RESULTS, "dashboard.html")) as src:
        with open(os.path.join(HERE, "dashboard.html"), "w") as dst:
            dst.write(src.read())

    cloud.stop()
    print("[done] results/ + dashboard.html ready. "
          f"Delivery rate: {summary['delivery_rate']:.1%} (simulated).")


if __name__ == "__main__":
    main()
